### PR TITLE
feat:Chromium support for Linux, Darwin and Windows

### LINKED ISSUE #45: Chromium support for Darwin and Windows
Version 0.1.8 supports Chromium on linux but not on Darwin and Windows.

### PR DESCRIPTION
**Pull request by gmoz22**
Add support for Chromium for Linux, Darwin and Windows platforms
Remove linux chromium binary lookup in Google Chrome
Closes #45

### CODE REVIEW

**Comment by zzo** [comment]
please rebase this against master thanks!

**Comment by greghuc** [comment]
+1 on removing chromium from chrome 'target'.

Just had a problem in my system where jasmine tests were passing locally under Chrome, but failing on remote Continuous Integration system.

Root cause was that CI system was using Chromium to run tests (and failing), rather than Chrome.

Current fix is to revert back to using karma-chrome-launcher@0.1.7

**Comment by Dignifiedquire** [comment]
@gmoz22 ping, re rebase onto master and please change to commit message to follow our [guidelines](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)

**Comment by Dignifiedquire** [comment]
@gmoz22 another ping

**Comment by rogeriopvl** [comment]
Closing this due to lack of feedback from the PR author. This issue was fixed and merged in #69.

**Pull request closed without merging**
