### PR TITLE
docs: update description about headless browsers

### PR DESCRIPTION
**Pull request by kmisha**
Please, have look at comments #237

### CODE REVIEW

**Comment by kmisha** [comment]
@googlebot I signed it!

**Review by mrsegen — APPROVED** [review]

**Comment by tehtea** [comment]
Hello, chanced upon this PR when searching on headless chrome with Karma. I think this is a useful addition, can it be merged?

**Comment by mrsegen** [comment]
Looks like the author may not have signed the contribution agreement. If you'd like, you could replicate the PR and sign the google contribution agreement to make this PR reviewable. (I'm on mobile at the moment and not able to do so myself.)

**Comment by tehtea** [comment]
Oh yea for sure, I can do that on my end too if @kmisha doesn't mind

**Comment by kmisha** [comment]
@tehtea yes, I don't have any objections.

**Review by Krinkle — APPROVED** [review]

**Pull request closed without merging**
