### PR TITLE
Allow --user-data-dir to be set in launcher properties

### PR DESCRIPTION
**Pull request by antigremlin**
Add a new `chromeDataDir` property to explicitly set the Chrome data
directory. Rationale:

Sometimes it is useful to run Chrome under Karma with certain plugins
loaded. One use-case is to have the **JetBrains IDE Support** plugin to
attach the IntelliJ debugger. We can do it with `--load-extension` but
this can also be prohibited by corporate policy. So one way to solve it
is to have the `--user-data-dir` point to a project subdirectory and to
install the plugin manually on the first run. It is preserved of course
on subsequent runs.

### CODE REVIEW

**Comment by antigremlin** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks, can you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) then I can merge it :)

**Comment by antigremlin** [comment]
@Dignifiedquire I think this you haven't noticed that the commit messages in this PR were corrected. Do you think you could merge this?

**Comment by Dignifiedquire** [comment]
Thanks :octocat: (yeah there are no notifications from github for pushes to PRs :( )

**Comment by schippie** [comment]
@antigremlin The fix is not published on NPM i tried pulling it and found out that the modifications made to the index.js are not present within the package that is installed from NPM. 

Which is problematic to say the least.

**Comment by dignifiedquire** [comment]
New version is out

**Comment by schippie** [comment]
A perfect thanks @dignifiedquire

**Pull request merged**
