### PR TITLE
Enable Automation for default Chrome Browser

### PR DESCRIPTION
**Pull request by rgant**
Trying to get rid of the save password prompt while running tests and this seems to be the flag to do it now.

### CODE REVIEW

**Comment by rgant** [comment]
I signed it!

**Comment by rogeriopvl** [comment]
Thanks for the PR @rgant 👍

**Comment by rogeriopvl** [comment]
@johnjbarton can we do a release with this?

**Comment by rgant** [comment]
In the mean time to get this functionality I've added the following customLauncher to my karma.conf.js:

```js
    customLaunchers: {
      AutomatedChrome: {
        base: 'Chrome',
        flags: ['--enable-automation'],
      },
      // https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/continuous-integration.md
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox'],
      },
    },
```

**Pull request merged**
