### PR TITLE
fix: add disable-renderer-backgrounding flag

### LINKED ISSUE #123: Launch Chrome with --disable-renderer-backgrounding flag
On macOS 10.12.4 and Chrome 58.0.3029, it appears that my test suite is slow down if Chrome is in the background. #64 should have fixed it a long ago, but a [comment](https://github.com/karma-runner/karma-chrome-launcher/issues/64#issuecomment-194455930) is mentioning the `--disable-renderer-backgrounding` flag, so I gave it a try, and it does fix my issue:

Before (Angular CLI project using Karma/Chrome):

```
05 05 2017 10:44:24.333:INFO [launcher]: Starting browser Chrome
05 05 2017 10:44:25.105:INFO [Chrome 58.0.3029 (Mac OS X 10.12.4)]: Connected on socket xKymjhyLh5832m9sAAAA with id 81470424
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (5.512 secs / 5.473 secs)
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (29.198 secs / 29.164 secs)
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (27.1 secs / 26.266 secs)
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (28.606 secs / 27.676 secs)
```

First run is fast, the following are really slow.

After, with this `karma.conf.js` using the `--disable-renderer-backgrounding` flag:
```js
    customLaunchers: {
      chromeBackground: {
        base: 'Chrome',
        flags: ['--disable-renderer-backgrounding']
      }
    },
    browsers: ['chromeBackground'],
```

The tests run faster:

```
05 05 2017 10:42:54.681:INFO [Chrome 58.0.3029 (Mac OS X 10.12.4)]: Connected on socket cAPHozikOSfUEEnpAAAA with id 83636627
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (5.666 secs / 5.628 secs)
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (6.864 secs / 6.831 secs)
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 102 of 102 SUCCESS (7.129 secs / 7.109 secs)
```

This may be related to the Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=605498#c1

### PR DESCRIPTION
**Pull request by cexbrayat**
Fixes #123

### CODE REVIEW

**Comment by rogeriopvl** [comment]
@cexbrayat thanks for the PR.

From what I understand, it should be enough to just use the `--disable-background-timer-throttling` flag, but on OSX it's not and it needs the `--disable-renderer-backgrounding` to completely disable that behaviour. Is it correct? If it is, then we need a comment documenting this work around.

I've been able to run a test suite with this flag and can confirm that there are performance gains that justify merging this.

**Comment by cexbrayat** [comment]
@rogeriopvl Thank you for considering this. You're correct, this only improves performance on OSX (https://bugs.chromium.org/p/chromium/issues/detail?id=605498#c1 is probably the Chrome related issue).

I added a comment to document the workaround, let me know if that's enough.

**Comment by rogeriopvl** [comment]
@cexbrayat looks good 👍

**Comment by rogeriopvl** [comment]
@dignifiedquire we should do a patch release

**Comment by dignifiedquire** [comment]
done

**Pull request merged**
