### PR TITLE
Allow headless to use GPU

### LINKED ISSUE #263: Chrome headless lost WebGL support on MacOS
Starting with Chrome 109, WebGL contexts can no longer be created in my Karma tests, meaning I can no longer run my tests locally. It appears to be because Chrome no longer supports software rendering on Arm-based macbooks, so the work-around is to enable the GPU instead: https://bugs.chromium.org/p/chromium/issues/detail?id=1407025#c9

I tried adding the indicated flags, but it's still not working because the launcher is also adding `--disable-gpu`: https://github.com/karma-runner/karma-chrome-launcher/blob/5f70a76de87ecbb57f3f3cb556aa6a2a1a4f643f/index.js#L172

Is there a reason the GPU should be disabled in headless mode? Is there a workaround for this, or can we remove this flag?

### PR DESCRIPTION
**Pull request by elalish**
Fixes #263 

It seems reasonable to allow headless chrome to use the GPU if available, and on M1 macbooks it's the only thing that works now for WebGL since Chrome 109. I've verified this allows my karma tests to run again on my M1 macbook as long as I also specify the `--use-angle=metal` flag.

### CODE REVIEW

**Comment by barrtender** [comment]
I believe this test will fail with this change: https://github.com/karma-runner/karma-chrome-launcher/blob/master/test/jsflags.spec.js#L85

The flag seems to have been added from the [original headless PR](https://github.com/karma-runner/karma-chrome-launcher/commit/744618184070c6d843a300e01e507d161dba3557) (6 years ago) and there's no specific note of it being load bearing so I don't see any reason for needing it.

**Comment by elalish** [comment]
Thanks, updated.

**Comment by elalish** [comment]
So, @barrtender do these test failures mean anything to you? I'm hoping this isn't related to my change...

**Comment by barrtender** [comment]
Did some investigation yesterday - I think it's just that the commit messages are in the wrong format. Can you rebase/squash the commits to get it in the standard format?

I suggest:
`fix(Mac WebGL): Allow headless to use GPU`

I think that would work.

**Comment by dollysingh3192** [comment]
Hey Guys,

Can we please merge it asap?

**Comment by pmvald** [comment]
@elalish We just need to re-format the commit messages to pass the commitlint test, then we'll merge it. I suggest we squash all these three commits into one with a message like  "feat: allow headless to use GPU" For more info on formatting see [this](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit-message-header) - you can also check previous commits.

**Comment by elalish** [comment]
Closing in favor of #266.

**Comment by elalish** [comment]
Also, there's a cool feature called "Squash and Merge" on Github to avoid this problem, though I suppose there's no getting around the picky commitlint.

**Pull request closed without merging**
