### PR TITLE
feat:Chromium support for Linux, Darwin and Windows

### LINKED ISSUE #45: Chromium support for Darwin and Windows
Version 0.1.8 supports Chromium on linux but not on Darwin and Windows.

### PR DESCRIPTION
**Pull request by haifengkao**
Add support for Chromium for Linux, Darwin and Windows platforms
Remove linux chromium binary lookup in Google Chrome
Closes #45

### CODE REVIEW

**Comment by haifengkao** [comment]
anyone here?

**Comment by dignifiedquire** [comment]
Thanks, can you please add some documentation about this to the readme and squash your commits?

**Comment by haifengkao** [comment]
I don't really get it. Do you want me to merge all commits into one?

**Comment by dignifiedquire** [comment]
All in one commit yes, see https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ for an example on how to

**Comment by dignifiedquire** [comment]
All in one commit yes, see https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ for an example on how to

**Comment by haifengkao** [comment]
done

**Pull request merged**
